<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Service 1.0</title>

        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css">
        <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>

        <script>
            $(document).ready(function() {
                $.mobile.initializePage();

                var sessionid = localStorage.getItem('service-session');
                if ( sessionid ) {
                    AuthBySessionId(sessionid);
                }

                $( "#vehicle-info-page" ).on('pageinit pageshow', function( event, ui ) {
                    var today = new Date()
                    var curHr = today.getHours()
                    var salutaion = 'Good Morning ';
                    if (curHr < 12) {
                        salutaion = 'Good Morning ';
                    } else if (curHr < 18) {
                        salutaion = 'Good Afternoon ';
                    } else {
                        salutaion = 'Good Evening ';
                    }
                    $('.customer-name').html(salutaion + localStorage.getItem('service-customer'));
                    if( $.cookie('service-session-id') === null ) {
                        alert('expired session');
                    } else {
                        var sessionid = getCookie('service-session-id');
                        alert(sessionid);
                    }
                });
            });
            $(document).bind("mobileinit", function () {
                $.mobile.autoInitializePage = false;
                $( ".save-btns" ).controlgroup({
                    type: "horizontal"
                });
            });
            function AuthBySessionId(sid) {
                if ( sid ) {
                    $.mobile.changePage("#vehicle-info-page", {
                        transition: "pop",
                        reverse: false,
                        changeHash: false
                    });
                }
            }
            function setCookie(cname, cvalue, exdays) {
                var d = new Date();
                d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
                var expires = "expires="+d.toUTCString();
                document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
            }

            function getCookie(cname) {
                var name = cname + "=";
                var ca = document.cookie.split(';');
                for(var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ') {
                        c = c.substring(1);
                    }
                    if (c.indexOf(name) == 0) {
                        return c.substring(name.length, c.length);
                    }
                }
                return "";
            }

            function checkCookie() {
                var user = getCookie("username");
                if (user != "") {
                    alert("Welcome again " + user);
                } else {
                    user = prompt("Please enter your name:", "");
                    if (user != "" && user != null) {
                        setCookie("username", user, 365);
                    }
                }
            }
        </script>
        <script src="js/starrating.js"></script>
        <script src="js/navigation.js"></script>
        <script src="js/login.js"></script>
        <script src="js/forgot.js"></script>
        <script src="js/rateprovider.js"></script>
        <script src="js/vehicleinfo.js"></script>

        <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
            }
            ul {
                margin: 0px;
                padding: 10px 0px 0px 0px;
            }

            li.star {
                list-style: none;
                display: inline-block;
                margin-right: 5px;
                cursor: pointer;
                color: #9E9E9E;
            }

            li.star.selected {
                color: #ff6e00;
            }

            .row-title {
                font-size: 20px;
                color: #00BCD4;
            }

            .review-note {
                font-size: 12px;
                color: #999;
                font-style: italic;
            }
            .row-item {
                margin-bottom: 20px;
                border-bottom: #F0F0F0 1px solid;
            }
            p.text-address {
                font-size: 12px;
            }
        </style>
    </head>
    <body>
        <!-- Start of first page -->
        <div data-role="page" id="home-page">

            <div data-role="header" data-position="fixed">
                <h1>Service 1.0</h1>
                <div data-role="navbar">
                    <ul>
                        <li><a href="#" class="nav-create-account" data-page="create-account">Create Account</a></li>
                        <li><a href="#" class="nav-login-in" data-page="login-in">Login in</a></li>
                    </ul>
                </div><!-- /navbar -->
            </div>

            <div role="main" class="ui-content">
                <p>
                    Our services and a way to search for the type of service they need
                </p>

                <p>
                    <div class="container">
                        <h4>Here's what customers think about some of our service providers!</h4>
                        <span id="dealer_list"></span>
                    </div>
                </p>
                <p>View internal page called <a href="#bar">bar</a></p>
                <p><a href="#" class="nav-contact-us" data-page="contact-us">Contact Us</a></p>
            </div><!-- /content -->

            <div data-role="footer" >
                <h4></h4>
            </div><!-- /footer -->
        </div><!-- /page -->

        <!-- Start of second page -->
        <div data-role="page" id="bar">

            <div data-role="header">
                <h1>Bar</h1>
            </div><!-- /header -->

            <div role="main" class="ui-content">
                <p>
                    I'm the second in the source order so I'm hidden when the page loads. I'm just shown if a link that references my id is beeing clicked.
                </p>
                <p><a href="#" class="nav-home">Back to home</a></p>
            </div><!-- /content -->

            <div data-role="footer">

            </div><!-- /footer -->
        </div><!-- /page -->

        <!-- Start of third page -->
        <div data-role="page" id="login-in-page">

            <div data-role="header">
                <h1>Log in</h1>
            </div><!-- /header -->

            <div role="main" class="ui-content">
                <p>
                    <form id="login-in-form">
                         <label for="login-in-email">Email:</label>
                         <input type="email" name="login-in-email" id="login-in-email" value="">
                         <label for="login-in-password">Password</label>
                         <input type="password" data-clear-btn="true" name="login-in-password" id="login-in-password" value="">
                         <input type="button" class="login-in-btn" value="Sign in">
                    </form>
                </p>
                <p><a href="#" class="nav-forgot" data-page="forgot">I forget my stuff</a></p>
                <p><a href="#" class="nav-home" data-page="home">Back to home</a></p>
                <p><a href="#">Contact Us</a></p>
            </div><!-- /content -->

            <div data-role="footer">

            </div><!-- /footer -->
        </div><!-- /page -->

        <!-- create account page -->
        <div data-role="page" id="create-account-page">

            <div data-role="header">
                <h1>Create Account</h1>
            </div><!-- /header -->

            <div role="main" class="ui-content">
                <p>
                    We take your data seriously! If you create an account we will:
                        Use your address to gelocate service centers near you
                        If you give us your mobile we will text you
                        If you give us your email we will email you
                </p>
                <p>
                <form id="create-account-form">
                    <label for="create-account-fname">First name:
                         <input type="text" name="create-account-fname" id="create-account-fname" value="">
                    </label>
                    <label for="create-account-lname">Last name:
                          <input type="text" name="create-account-lname" id="create-account-lname" value="">
                    </label>
                    <label for="create-account-mobile">Mobile:
                          <input type="text" name="create-account-mobile" id="create-account-mobile" value="">
                    </label>
                    <label for="create-account-zip">Zip Code:
                          <input type="text" name="create-account-zip" id="create-account-zip" value="">
                    </label>
                    <label for="create-account-email">Email:
                          <input type="text" name="create-account-email" id="create-account-email" value="">
                    </label>
                         <label for="create-account-password">Create password</label>
                         <input type="password" data-clear-btn="true" name="create-account-password" id="create-account-password" value="">
                    <label for="create-account-password-cnfm">Confirm password</label>
                         <input type="password" data-clear-btn="true" name="create-account-password-cnfm" id="create-account-password-cnfm" value="">


                    <fieldset data-role="controlgroup" data-type="horizontal">
                        <legend>My prefered communication:</legend>
                        <input type="radio" name="communication" id="communication-email" value="email" checked="checked">
                        <label for="communication-email">Email me</label>
                        <input type="radio" name="communication" id="communication-mobile" value="mobile">
                        <label for="communication-mobile">Text my mobile</label>
                        <input type="radio" name="communication" id="communication-site" value="site">
                        <label for="communication-site">I'll use the site</label>
                    </fieldset>

                    <input type="button" id="create-account-btn" value="Sign up">
                </form>
                </p>
                <p><a href="#" class="nav-log-in" data-page="log-in">I am a member - log in</a></p>
                <p><a href="#" class="nav-home" data-page="home">Back to home</a></p>
                <p><a href="#" class="nav-contact-us" data-page="contact-us">Contact Us</a></p>
            </div><!-- /content -->

            <div data-role="footer">

            </div><!-- /footer -->
        </div><!-- /page -->


        <!-- Start of third page -->
        <div data-role="page" id="forgot-page">

            <div data-role="header">
                <h1>Forgot Password</h1>
            </div><!-- /header -->

            <div role="main" class="ui-content">
                <p>
                    Forgot your password? We'll send you a link! (it expires in 24 hours)
                </p>
                <p>
                <form id="forgot-form">
                    <label for="forgot-email">Email:</label>
                     <input type="email" name="forgot-email" id="forgot-email" value="">
                    <input type="button" id="forgot-btn" value="Send me a link">
                </form>
                </p>
                <p><a href="#" class="nav-home" data-page="home">Back to home</a></p>
                <p><a href="#" class="nav-contact-us" data-page="contact-us">Contact Us</a></p>
            </div><!-- /content -->

            <div data-role="footer">

            </div><!-- /footer -->
        </div><!-- /page -->


        <!-- Start of third page -->
        <div data-role="page" id="vehicle-info-page">

            <div data-role="header">
                <h1>Vehicle Information</h1>
            </div><!-- /header -->

            <div role="main" class="ui-content">
                <p>
                    <div class="customer-name"></div>
                    Please enter your Vehicle Information so we can look up your vehicle
                </p>
                <p>
                <form id="vehicle-info-form">
                    <label for="vehicle-info-year">Vehicle Year:</label>
                    <input type="text" name="vehicle-info-year" id="vehicle-info-year" value="">
                    <label for="vehicle-info-make">Vehicle Make:</label>
                    <input type="text" name="vehicle-info-make" id="vehicle-info-make" value="">
                    <label for="vehicle-info-model">Vehicle Model:</label>
                    <input type="text" name="vehicle-info-model" id="vehicle-info-model" value="">
                    <label for="vehicle-info-vin">Vehicle VIN:</label>
                    <input type="text" name="vehicle-info-vin" id="vehicle-info-vin" value="">
                    <input type="button" id="vehicle-info-btn" value="Submit">
                </form>
                </p>
                <p><a href="#" class="nav-home" data-page="home">Back to home</a></p>
                <p><a href="#" class="nav-contact-us" data-page="contact-us">Contact Us</a></p>
            </div><!-- /content -->

            <div data-role="footer" style="visibility: hidden;">

            </div><!-- /footer -->
        </div><!-- /page -->


        <!-- Start of third page -->
        <div data-role="page" id="rate-provider-page">

            <div data-role="header">
                <h1>Rate your service provider</h1>
            </div><!-- /header -->

            <div role="main" class="ui-content">
                <p>
                    Please take the time to rate:

                    <div id="your-service-provider"></div>
                </p>
                <p><a href="#" class="nav-home" data-page="home">Back to home</a></p>
                <p><a href="#">Contact Us</a></p>
            </div><!-- /content -->

            <div data-role="footer" style="visibility: hidden;">

            </div><!-- /footer -->
        </div><!-- /page -->


        <!-- Start of third page -->
        <div data-role="page" id="contact-us-page">

            <div data-role="header">
                <h1>Contact Us</h1>
            </div><!-- /header -->

            <div role="main" class="ui-content">
                <p>
                    You may email us at:
                    or call at 888 888 8888
                </p>
                <p><a href="#" class="nav-home" data-page="home">Back to home</a></p>
                <p><a href="#">Contact Us</a></p>
            </div><!-- /content -->

            <div data-role="footer" style="visibility: hidden;">

            </div><!-- /footer -->
        </div><!-- /page -->


    </body>
</html>
